#pragma once

enum EnemyAnimation {
	
	ANIMATION_IDDLE,
    ANIMATION_WALKING,
    ANIMATION_RUNNING_AWAY,
    ANIMATION_CHARGIN_LUNGE,
    ANIMATION_LUNGING,
    ANIMATION_MELEE,
    ANIMATION_DISTANCE
};