#pragma once

enum GameObjectType {
    NONE,

    // CRYSTALS
    COIN_1      = 1,
    COIN_5      = 5,
    COIN_20     = 20,
    COIN_50     = 50,
    COIN_100    = 100,
    COIN_200    = 200,
    COIN_500    = 500,

    // ENEMYS
    ENEMY_PIG,
    ENEMY_RODENT,
    ENEMY_PINEAPPLE,
    ENEMY_SPIDER,
    ENEMY_MONKEY,
    ENEMY_GHOST,

    // MELEE WEAPONS
    MELEE_SWORD,
    MELEE_MACE,
    MELEE_STICK,

    // DISTANCE WEAPONS
    DISTANCE_BOW,
    DISTANCE_BLOWGUN,
    DISTANCE_SLINGSHOT,
    DISTANCE_PLASMAGUN,

    // ATTACKS
    ATTACK_MELEE,
    ATTACK_DISTANCE,

    // CHESTS
    CHEST_COIN_CASTLE,
    CHEST_COIN_CAR,
    CHEST_COIN_LATRINE,
    CHEST_COIN_BAG,
    CHEST_WEAPON_MACE,
    CHEST_WEAPON_SWORD,
    CHEST_WEAPON_BOW_SKELETON,

    // OBSTACLES
    OBSTACLE_1,
    OBSTACLE_2,

    OBSTACLE_B1_1,
    OBSTACLE_B1_2,
    OBSTACLE_B1_3,
    OBSTACLE_B1_4,
    OBSTACLE_B1_5,
    OBSTACLE_B1_6,
    OBSTACLE_B2_1,
    OBSTACLE_B2_2,
    OBSTACLE_B2_3,
    OBSTACLE_B2_4,
    OBSTACLE_B2_5,
    OBSTACLE_B2_6,
    OBSTACLE_B3_1,
    OBSTACLE_B3_2,
    OBSTACLE_B3_3,
    OBSTACLE_B3_4,
    OBSTACLE_B3_5,
    OBSTACLE_B3_6,
    OBSTACLE_B4_1,
    OBSTACLE_B4_2,
    OBSTACLE_B4_3,
    OBSTACLE_B4_4,
    OBSTACLE_B4_5,
    OBSTACLE_B4_6,
    OBSTACLE_B5_1,
    OBSTACLE_B5_2,
    OBSTACLE_B5_3,
    OBSTACLE_B5_4,
    OBSTACLE_B5_5,
    OBSTACLE_B5_6,

    // INTERES POINTS
    INTERESTPOINT_B1_1,
    INTERESTPOINT_B1_1_P1,
    INTERESTPOINT_B1_1_P2,
    INTERESTPOINT_B1_1_P3,
    INTERESTPOINT_B1_1_P4,
    INTERESTPOINT_B1_1_P5,
    INTERESTPOINT_B1_2,
    INTERESTPOINT_B1_2_P1,
    INTERESTPOINT_B1_2_P2,
    INTERESTPOINT_B1_2_P3,
    INTERESTPOINT_B1_2_P4,
    INTERESTPOINT_B1_2_P5,
    INTERESTPOINT_B1_3,
    INTERESTPOINT_B1_3_P1,
    INTERESTPOINT_B1_3_P2,
    INTERESTPOINT_B1_3_P3,
    INTERESTPOINT_B1_3_P4,
    INTERESTPOINT_B1_3_P5,

    INTERESTPOINT_B2_1,
    INTERESTPOINT_B2_1_P1,
    INTERESTPOINT_B2_1_P2,
    INTERESTPOINT_B2_1_P3,
    INTERESTPOINT_B2_1_P4,
    INTERESTPOINT_B2_1_P5,
    INTERESTPOINT_B2_2,
    INTERESTPOINT_B2_2_P1,
    INTERESTPOINT_B2_2_P2,
    INTERESTPOINT_B2_2_P3,
    INTERESTPOINT_B2_2_P4,
    INTERESTPOINT_B2_2_P5,
    INTERESTPOINT_B2_3,
    INTERESTPOINT_B2_3_P1,
    INTERESTPOINT_B2_3_P2,
    INTERESTPOINT_B2_3_P3,
    INTERESTPOINT_B2_3_P4,
    INTERESTPOINT_B2_3_P5,

    INTERESTPOINT_B3_1,
    INTERESTPOINT_B3_1_P1,
    INTERESTPOINT_B3_1_P2,
    INTERESTPOINT_B3_1_P3,
    INTERESTPOINT_B3_1_P4,
    INTERESTPOINT_B3_1_P5,
    INTERESTPOINT_B3_2,
    INTERESTPOINT_B3_2_P1,
    INTERESTPOINT_B3_2_P2,
    INTERESTPOINT_B3_2_P3,
    INTERESTPOINT_B3_2_P4,
    INTERESTPOINT_B3_2_P5,
    INTERESTPOINT_B3_3,
    INTERESTPOINT_B3_3_P1,
    INTERESTPOINT_B3_3_P2,
    INTERESTPOINT_B3_3_P3,
    INTERESTPOINT_B3_3_P4,
    INTERESTPOINT_B3_3_P5,

    INTERESTPOINT_B4_1,
    INTERESTPOINT_B4_1_P1,
    INTERESTPOINT_B4_1_P2,
    INTERESTPOINT_B4_1_P3,
    INTERESTPOINT_B4_1_P4,
    INTERESTPOINT_B4_1_P5,
    INTERESTPOINT_B4_2,
    INTERESTPOINT_B4_2_P1,
    INTERESTPOINT_B4_2_P2,
    INTERESTPOINT_B4_2_P3,
    INTERESTPOINT_B4_2_P4,
    INTERESTPOINT_B4_2_P5,
    INTERESTPOINT_B4_3,
    INTERESTPOINT_B4_3_P1,
    INTERESTPOINT_B4_3_P2,
    INTERESTPOINT_B4_3_P3,
    INTERESTPOINT_B4_3_P4,
    INTERESTPOINT_B4_3_P5,

    INTERESTPOINT_B5_1,
    INTERESTPOINT_B5_1_P1,
    INTERESTPOINT_B5_1_P2,
    INTERESTPOINT_B5_1_P3,
    INTERESTPOINT_B5_1_P4,
    INTERESTPOINT_B5_1_P5,
    INTERESTPOINT_B5_2,
    INTERESTPOINT_B5_2_P1,
    INTERESTPOINT_B5_2_P2,
    INTERESTPOINT_B5_2_P3,
    INTERESTPOINT_B5_2_P4,
    INTERESTPOINT_B5_2_P5,
    INTERESTPOINT_B5_3,
    INTERESTPOINT_B5_3_P1,
    INTERESTPOINT_B5_3_P2,
    INTERESTPOINT_B5_3_P3,
    INTERESTPOINT_B5_3_P4,
    INTERESTPOINT_B5_3_P5,

    //SECURE ZONE
    SECURE_ZONE_IP,
    SECURE_ZONE_TOWN,

    // KEYS
    KEY_BIOME1,
    KEY_BIOME2,
    KEY_BIOME3,
    KEY_BIOME4,
    KEY_BIOME5,

    // EGGS
    EGG_BIOME1,
    EGG_BIOME2,
    EGG_BIOME3,
    EGG_BIOME4,
    EGG_BIOME5,

    //MESSAGEBOX
    MESSAGEBOX_UPDATER,
    MESSAGEBOX_BANK,

    //NOTIFICATIONS
    NOTIFICATION_NOCOINS,
    NOTIFICATION_LEVEL_UP_SOUND,
    NOTIFICATION_BANK_DEPOSITOR,
    NOTIFICATION_BANK_EXTRACTOR,
    NOTIFICATION_FAILEGG,
    NOTIFICATION_FAILDOOR,

    //NPCS
    NPC_SHAMAN_B0_STATSUPDATER, //NPC STATS UPDATER
    NPC_OLDMAN_B0_STICK,
    NPC_MOTHER_B0_INFORMATION,
    NPC_GUITARIST_B0_COMPASS,
    NPC_FARMER_B1_SLINGSHOT,
    NPC_GENTLEMAN_B1_KEY,
    NPC_COWBOY_B2_MAP,
    NPC_PIRATE_B2_COINS,
    NPC_FUMIGATOR_B3_COINS,
    NPC_INDIAN_B3_BLOWGUN,
    NPC_ROBOT_B4_INFORMATION,
    NPC_SKELETON_B5_COINS,

    //VILLAGE_OBSTACLE_TIPES
    VILLAGE_OBSTACLE_SHAMAN_ENVIRONMENT,
    VILLAGE_OBSTACLE_SCARECROW, // espantapajaros
    VILLAGE_OBSTACLE_HOUSE1,
    VILLAGE_OBSTACLE_WINDMILL,  // molino
    VILLAGE_OBSTACLE_WATERMILL, // noria
    VILLAGE_OBSTACLE_FENCE,     // valla
    VILLAGE_OBSTACLE_WELL,      // pozo
    VILLAGE_OBSTACLE_WEAPON_HOLDER, // soporte armas
    VILLAGE_OBSTACLE_BARREL,    // barril abierto
    VILLAGE_OBSTACLE_BARREL2,   // barril cerrado
    VILLAGE_OBSTACLE_MEDICTEND,   // tienda medico
    VILLAGE_OBSTACLE_DANGER,   // Signal of danger at end of B1

    //DETECTION SIGNS
    DETECTIONSIGN_INTERROGATION,
    DETECTIONSIGN_EXCLAMATION,
    DETECTIONSIGN_IMPROVER,

    //SOUND EVENTS
    MUSIC_AMBIENT,
    AMBIENT_SFX,
    SOUNT_HEART,
    
    COMPASS_SOUND,
    PLAYER_ACTIONS,
    
    WIN_SOUND_SHOOT,
    GAMEOVER_SOUND_SHOOT,

    //LIGHTS
    LIGHT_DIRECTIONAL,
    LIGHT_POINT, 
    LIGHT_MOUSE,
    LIGHT_CRISTAL,
    LIGHT_ILUMINATION
};